### PR TITLE
Particle Detour

### PR DESCRIPTION
**Pull request by Gabriel-Morales805**

### CODE REVIEW

**Comment by Mee12345** [comment]
why are GetParticleEmitter and ParticleEmitter detoured?

**Comment by Gabriel-Morales805** [comment]
@Mee12345 I will do some testing, as for what they do,

the GetParticleEmitter and ParticleEmitter functions are being detoured in order to add some additional functionality to them. For example, the GetPos function is being detoured to add support for chunk offsets, which are used to store the position of an entity or object relative to a particular chunk in the map. Similarly, the StartParticleEffect and StopParticleEffect functions are being detoured to allow them to work with entities that have chunk offsets.

**Comment by Gabriel-Morales805** [comment]
@Mee12345 I beleive it does work from my testing, but anywho, have a good rest of your week mr mee.

**Comment by Mee12345** [comment]
im confused, the getparticlepos detour doesn’t run anything else other than the original function, what is the point of it?

**Comment by Gabriel-Morales805** [comment]
@Mee12345

**Pull request closed without merging**
