### PR TITLE
Update to inf_chunks_sv.lua

### PR DESCRIPTION
**Pull request by willfromlondon**
Added angle get/set while teleporting and changed order of functions, this fixes ballsocket and high-speed prop misalignment that can happen with more complex contraptions, and makes the teleport smoother.

### CODE REVIEW

**Comment by Mee12345** [comment]
looks amazing, has this been tested thoroughly?

**Comment by willfromlondon** [comment]
I was actually working on something sort of similar to this addon, but this is way beyond what I had! This was the method I figured out after my contraptions(wheels and prop engines mostly) kept detonating when teleporting.

Mostly tested with custom built stuff - prop engine cars / planes etc. No issues with ballsocket wheels / parented props, and it seems to work absolutely fine with simfphys. Haven't done a huge amount of testing with wac but I can't see why it wouldn't.

**Comment by willfromlondon** [comment]
Just did some more testing on wac/simphys, seems to work absolutely fine from what I could see.

**Comment by Mee12345** [comment]
awesome, ill merge when I get the time to test

**Comment by pizzamagician** [comment]
works better with prop vehicles

**Comment by pizzamagician** [comment]
velocity gets cut in half when transitioning between chunks

**Comment by DarianLStephens** [comment]
Is that something which can be fixed? Because I see prop vehicles being a big attraction, especially flying ones. If they have their speed cut and need to get back up again, it will severely limit the max speed you can travel at.
Even if it's a soft limit, you can still only travel so far, and speed up so much, before hitting another chunk and being reduced.

**Comment by willfromlondon** [comment]
In my testing with prop vehicles with this fix, the speed is maintained nearly perfectly - what kind of contraptions are you using?

**Comment by DarianLStephens** [comment]
Personally, a flying ship thing controlled by thrusters, with the gravity hull designator used for the inside.
Maybe this problem is why it never seemed to go as fast as I thought it should? I never noticed the issue in the first place beyond that.

**Pull request merged**
