### PR TITLE
Add Documentation

### PR DESCRIPTION
**Pull request by MyUsernamee**
Add some documentation

### CODE REVIEW

**Review by Mee12345 — CHANGES_REQUESTED** [review]
Use C style COmmenting

**Review by MyUsernamee — COMMENTED** [review]
Looked at it

**Review by Mee12345 — COMMENTED** [review]
ITS STILL NOT C

**Comment by Mee12345** [comment]
I KNOW GARRY SUX BUT USE   C

USE LIKE /// INSTEAd o f --

**Comment by keganpowers34** [comment]
@MyUsernamee **///**

**Comment by MyUsernamee** [comment]
#-- Is better than //

## Reason 1

-- is better than // in markdown because it is a more semantically meaningful way to denote a line break. // is typically used to denote a new paragraph, which may be confusing for readers. 

In addition, // may not render properly in all browsers and devices, whereas -- is more likely to display consistently. 

-- is also the HTML code for a horizontal line, which can be useful for visually separating sections of text. 

Overall, -- is a more versatile and semantically meaningful way to denote a line break. 

## Reason 2

-- is also the HTML code for a horizontal line, which can be useful for visually separating sections of text 
-- is the more semantically meaningful way to denote a line break 
-- is more likely to display consistently across browsers and devices 
-- is more versatile than // 

## Conclusion

Therefore, -- is better than //.

**Comment by keganpowers34** [comment]
6xONNNZXinc

**Comment by keganpowers34** [comment]
https://user-images.githubusercontent.com/42286354/197663434-e4851fc0-d501-4fa7-8f95-2047624cb193.mp4

@MyUsernamee

**Comment by Mee12345** [comment]
I DONT CARE USE C

**Comment by Mee12345** [comment]
ITS ME CODE

**Comment by MyUsernamee** [comment]
:(

**Comment by MyUsernamee** [comment]
FINE!

**Comment by keganpowers34** [comment]
Uploading discordrepost_20211115_18.mp4…

**Comment by keganpowers34** [comment]
https://user-images.githubusercontent.com/42286354/197663537-9fa52c9b-0218-47fa-be2c-35694b47496f.mp4

**Comment by keganpowers34** [comment]
RainbowMonke

**Comment by keganpowers34** [comment]
https://user-images.githubusercontent.com/42286354/197663639-0d7b4a0a-de24-4e7e-b9d4-34a084d452be.mp4

**Comment by MyUsernamee** [comment]
REOPEN

**Comment by keganpowers34** [comment]
https://user-images.githubusercontent.com/42286354/197663741-a0641413-12b7-44e5-8816-07a2c9b75575.mp4

**Comment by MyUsernamee** [comment]
OK

**Comment by keganpowers34** [comment]
termopasta

**Comment by keganpowers34** [comment]
https://user-images.githubusercontent.com/42286354/197663938-03ac6dde-a614-4e1b-bb18-29fd4c0c8331.mp4

**Comment by keganpowers34** [comment]
Uploading video0_1.mp4…

**Comment by keganpowers34** [comment]
https://user-images.githubusercontent.com/42286354/197664056-5fe20914-0d0e-4c74-b40d-ec3d9a0988fb.mp4

**Review by MyUsernamee — COMMENTED** [review]
Ok

**Comment by keganpowers34** [comment]
https://user-images.githubusercontent.com/42286354/197664104-7254afc9-8d64-489b-9c5d-b95912f9f3a4.mp4

@MyUsernamee

**Comment by Mee12345** [comment]
GONE FOREVER

**Comment by keganpowers34** [comment]
> GONE FOREVER


https://user-images.githubusercontent.com/42286354/197664378-f3eb7a0c-8b15-4aaa-8c84-25e93b88a0c8.mp4

**Pull request closed without merging**
