### PR TITLE
obj world offset

### PR DESCRIPTION
**Pull request by Def-Try**
i am sorry if this is worse than i thought, but parser needs world offset if we want to make infmaps with cities or something like that

### CODE REVIEW

**Comment by OBRISON** [comment]
This seems pointless.
Why not move the whole map in blender instead?

**Comment by Def-Try** [comment]
maybe not just maps? or duplication of maps on random positions?

**Comment by Mee12345** [comment]
currently the obj loader does not support collision on multiple map models

your code isnt terrible, but it doesnt really work currently in the way you think it will work

ill leave it open since it seems like i need to add this as an option at some point

**Comment by Def-Try** [comment]
Well, I tested it and seems like collision works in 50% of parses.

**Comment by Mee12345** [comment]
A custom matrix has been implemented allowing for custom scale, rotation, and translation so this is obsolete 

Thanks for "suggesting" though!

**Pull request closed without merging**
