### PR TITLE
Fixed collision groups

### LINKED ISSUE #12: rpgs in general are screwed
maybe use manual SetVelocity on all RPGS?

### PR DESCRIPTION
**Pull request by RaphaelIT7**
Fixed the collision groups which were broken.
RPGs(fixes #12), Grenades, Bug Bait and some weird slams collisions

### CODE REVIEW

**Review by Mee12345 — CHANGES_REQUESTED** [review]
(first time using github review so sorry if i do this wrong..)

this is great, but i have a concern

collision groups are already handled internally by the engine when you return 'nil' in the ShouldCollide hook, there is no need for a custom function to do it for you, this means by default we should be returning 'nil' instead of 'true', this is also good for support with other addons since they may also call the same hook

the reason the RPG doesn't collide with anything (except the terrain) is because its chunk data is never set and therefore succeeds on the "ent1.CHUNK_OFFSET != ent2.CHUNK_OFFSET" condition (which returns false), i simpily need to set its chunk data when it is created and it should work as intended, I just haven't bothered to add an exception for the RPG (or crossbow bolt) yet

**Comment by RaphaelIT7** [comment]
**"I just haven't bothered to add an exception for the RPG (or crossbow bolt) yet"**
it seems to work now when you remove it from the filter without changing anything else

**"collision groups are already handled internally by the engine when you return 'nil' in the ShouldCollide hook"**
because the engine handles them already, only a few of them had to be adjusted, and you return true or false. so you already override it.
collision groups like COLLISION_GROUP_IN_VEHICLE got broken, and the hook returned true instead of false 

**"this is also good for support with other addons since they may also call the same hook"**
if an addon uses this hook and changes the collision of every entity and not a specified one, it will override your hook.

This overrides it.
```lua
hook.Add("ShouldCollide", "Example", function(ent1, ent2)
        return true
end)
```

This overrides it only for a specified one
```lua
hook.Add("ShouldCollide", "Example", function(ent1, ent2)
        if ent1:GetClass() == "prop_physics" then
                return false
        end
end)
```

**Comment by Mee12345** [comment]
I don't think I ever return true

**Comment by RaphaelIT7** [comment]
not needed anymore

**Pull request closed without merging**
